In [19]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold, GridSearchCV as GS_CV
from sklearn.metrics import confusion_matrix as CM

In [32]:
dataset = datasets.load_iris()
X, y = dataset['data'], dataset['target']
X_tr,X_ts, y_tr,y_ts = train_test_split(X,y,test_size=0.4)

In [33]:
svc    = svm.SVC()
params = {'kernel':('linear','rbf'), 'C':[1,10,100]}
clf    = GS_CV(svc, params)

In [42]:
clf.fit(X_tr, y_tr)
pred = clf.predict(X_ts)
print(CM(y_ts, pred))
acc = clf.score(X_ts, y_ts) # gives directly the accuracy score.
print(f'the accuracy is {acc}')

[[17  0  0]
 [ 0 20  1]
 [ 0  0 22]]
the accuracy is 0.9833333333333333
